### ISSUE TITLE
Error about "ValueError: start out of range (-265)"

### ISSUE THREAD

**Issue by fjmuzengyiheng** [bcgsc/straglr#18]
hi, @readmanchiu 
Thank you for this useful tool. An error occurred when I called STR using nanopore sequencing data.
Could you please help me with this? Thank you so much!

multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.10/site-packages/pathos/helpers/mp_helper.py", line -1, in <lambda>
  File "/usr/local/lib/python3.10/site-packages/src/tre.py", line 869, in get_alleles
    for aln in bam.fetch(locus[0], locus[1] - split_neighbour_size, locus[2] + split_neighbour_size):
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 690, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-265)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/straglr.py", line 86, in <module>
    main()
  File "/usr/local/bin/straglr.py", line 79, in main
    variants = tre_finder.genotype(args.loci)
  File "/usr/local/lib/python3.10/site-packages/src/tre.py", line 1130, in genotype
    return self.collect_alleles(loci)
  File "/usr/local/lib/python3.10/site-packages/src/tre.py", line 1104, in collect_alleles
    batched_results = parallel_process(self.get_alleles, batches, self.nprocs)
  File "/usr/local/lib/python3.10/site-packages/src/utils.py", line 21, in parallel_process
    results = p.map(func, args)
  File "/usr/local/lib/python3.10/site-packages/pathos/multiprocessing.py", line 139, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
ValueError: start out of range (-265)

**Comment by readmanchiu** [comment]
Hi @fjmuzengyiheng, the new version (v1.4.0) should hopefully fix this. Please try and let me know if it doesn't.
Thanks!

**Comment by fjmuzengyiheng** [comment]
> Hi @fjmuzengyiheng, the new version (v1.4.0) should hopefully fix this. Please try and let me know if it doesn't. Thanks!

Thank you for fixing this. It works well now. : )

**Comment by readmanchiu** [comment]
Thanks @fjmuzengyiheng I'll close the issue now
