### ISSUE TITLE
genome-scan: IndexError: list index out of range

### ISSUE THREAD

**Issue by lfearnley** [bcgsc/straglr#44]
Encountering an issue on data from the ONT 1KG Vienna cohort. I've pulled the CRAMs, dumped to fastq, realigned with minimap2, then run straglr in scan mode as follows:

```
python /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/straglr.py ${cramFile}.cram ${params.reference} ${cramFile}_straglr_scan --min_str_len 2 --max_str_len 100 --min_ins_size 60 --genotype_in_size --min_support 2 --max_num_clusters 2 --nprocs ${task.cpus-1}
```

I get the following error:

```
  /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/ins.py:189: UserWarning: multiple_iterators not implemented for CRAM
    for pileup_col in bam.pileup(region[0], int(region[1]), int(region[2])):
  /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/ins.py:189: UserWarning: multiple_iterators not implemented for CRAM
    for pileup_col in bam.pileup(region[0], int(region[1]), int(region[2])):
  /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/ins.py:189: UserWarning: multiple_iterators not implemented for CRAM
    for pileup_col in bam.pileup(region[0], int(region[1]), int(region[2])):
  /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/ins.py:189: UserWarning: multiple_iterators not implemented for CRAM
    for pileup_col in bam.pileup(region[0], int(region[1]), int(region[2])):
  /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/ins.py:189: UserWarning: multiple_iterators not implemented for CRAM
    for pileup_col in bam.pileup(region[0], int(region[1]), int(region[2])):
  /vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/ins.py:189: UserWarning: multiple_iterators not implemented for CRAM
    for pileup_col in bam.pileup(region[0], int(region[1]), int(region[2])):
  multiprocess.pool.RemoteTraceback: 
  """
  Traceback (most recent call last):
    File "/vast/projects/fearnleyl_ukbiobank/miniconda/envs/straglr/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
    File "/vast/projects/fearnleyl_ukbiobank/miniconda/envs/straglr/lib/python3.10/site-packages/multiprocess/pool.py", line 48, in mapstar
      return list(map(*args))
    File "/vast/projects/fearnleyl_ukbiobank/miniconda/envs/straglr/lib/python3.10/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
      func = lambda args: f(*args)
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/tre.py", line 153, in extract_tres
      expansions = self.analyze_trf(grouped_results, target_flank, unpaired_clips)
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/tre.py", line 164, in analyze_trf
      same_pats = self.find_similar_long_patterns_ins(results)
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/tre.py", line 194, in find_similar_long_patterns_ins
      same_pats = self.parse_pat_blastn(blastn_out)
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/tre.py", line 593, in parse_pat_blastn
      pid = float(cols[2])
  IndexError: list index out of range
  """
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/straglr.py", line 101, in <module>
      main()
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/straglr.py", line 89, in main
      variants = tre_finder.examine_ins(ins, min_expansion=args.min_ins_size)
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/tre.py", line 1351, in examine_ins
      batched_results = parallel_process(self.extract_tres, batches, self.nprocs)
    File "/vast/scratch/users/fearnley.l/1KG_ONT_VIENNA/straglr/src/utils.py", line 21, in parallel_process
      results = p.map(func, args)
    File "/vast/projects/fearnleyl_ukbiobank/miniconda/envs/straglr/lib/python3.10/site-packages/pathos/multiprocessing.py", line 135, in map
      return _pool.map(star(f), zip(*args)) # chunksize
    File "/vast/projects/fearnleyl_ukbiobank/miniconda/envs/straglr/lib/python3.10/site-packages/multiprocess/pool.py", line 367, in map
      return self._map_async(func, iterable, mapstar, chunksize).get()
    File "/vast/projects/fearnleyl_ukbiobank/miniconda/envs/straglr/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
      raise self._value
  IndexError: list index out of range
```

**Comment by HLHsieh** [comment]
Hi there,

I just want to report that I also have the similar issue on genotype mode (locus given).

```
Traceback (most recent call last):
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/straglr.v1.5/straglr.py", line 101, in <module>
    main()
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/straglr.v1.5/straglr.py", line 98, in main
    tre_finder.output_vcf(variants, '{}.vcf'.format(args.out_prefix))
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/straglr.v1.5/src/tre.py", line 1513, in output_vcf
    fails = Variant.find_fails(variants)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/turbo/umms-kinfai/hsinlun/bin/straglr.v1.5/src/variant.py", line 244, in find_fails
    failed_reason = Counter(failed_reasons).most_common(1)[0][0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by readmanchiu** [comment]
looks like some temporary blastn tabular output is truncated. Not sure why that is possible, I checked some of the blastn outputs, either they are empty or have all the columns filled.
Maybe you can run in debug mode and specify a custom temp directory to store all the temp files produced (`--debug --tmpdir your_path`), tar up the temp directory and attached the tarball for me to have a look?

**Comment by lfearnley** [comment]
@readmanchiu Generating that now, sorry for the delay. On inspection of that sample in isolation there's a couple of blastn core dumps being generated for reasons I haven't quite been able to figure out yet.

**Comment by readmanchiu** [comment]
I usually use `--exclude` to exclude some very repetitive regions like the centromeres, regions heavily populated with long repeats, and even long segdups because the mappings cannot be confident.
The blastn alignments were done to compare TRs identified from insertions initially against all the reads that were mapped to the locus for in the genotyping phase.  
I saw this could go awry if the locus was one of such "difficult" regions with erroneously-high cover or very long repeat motifs.  Therefore I chose to identify such regions a priori and skip analysis on them.
I suspect this may be the cause of the failed blastn jobs. You might consider skipping these problematic regions that are likely to get very low returns for you.

**Comment by lfearnley** [comment]
Thanks! I'll try that before packing up a temp dir.

Would an alternative to this be to implement changes to the way blastn is invoked by handling failure to return results so it doesn't take STRaglr down, or are there other failure modes that are being picked up by this?

**Comment by readmanchiu** [comment]
yeah, I'll probably add some code to make the run continues despite blastn failure(s)
Just found out that I didn't put an upper bound of the motif length before subject them to blastn, which can be a problem for those repeat-crazy regions as mentioned.

**Comment by lfearnley** [comment]
I've updated to 1.5.1 and tried the exclusion list - the sample that was failing has run successfully, so I'll hold this open until I clear the other 1000 samples just to confirm that it's fixed the problems.

Might it be worth updating the genome-scan docs to note that the exclude argument is necessary for that mode?

**Comment by readmanchiu** [comment]
Thanks very much for testing, will update the docs shortly

**Comment by lfearnley** [comment]
That's fixed it - it's run smoothly on the 1KG Vienna data now. Thanks for the help!
